name: comment-pr

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
on:
  workflow_run:
    workflows: ["receive-pr"]
    types:
      - completed

# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
jobs:
  post-suggestions:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.workflow_run.head_branch}}
          repository: ${{github.event.workflow_run.head_repository.full_name}}

      # Download the patch
      - uses: actions/download-artifact@v4
        with:
          name: patch
          github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          run-id: ${{ github.event.workflow_run.id }}
      - name: Apply patch
        run: |
          git apply git-diff.patch --allow-empty
          rm git-diff.patch

      # Post suggestions as a comment on the PR
      - uses: googleapis/code-suggester@v2
        with:
          command: review
          pull_number: ${{ github.event.number }}
          git_dir: '.'
