name: comment-pr

on:
  workflow_run:
    workflows: ["receive-pr"]
    types:
      - completed

# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
jobs:
  post-suggestions:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.workflow_run.head_branch}}
          repository: ${{github.event.workflow_run.head_repository.full_name}}
      - uses: actions/download-artifact@v4
        with:
          name: patch
          github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          run-id: ${{ github.event.workflow_run.id }}

      - name: Apply patch
        run: |
          git apply git-diff.patch --allow-empty
          rm git-diff.patch

      - uses: googleapis/code-suggester@v2
        with:
          command: review
          pull_number: ${{ github.event.workflow_run.pull_requests[0].number }}
          git_dir: '.'
