name: receive-pr

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
jobs:
  upload-patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'gradle'

      # Apply license headers and capture the diff
      - name: Check licenses
        run: ./gradlew licenseFormat
      - name: Create patch
        run: git diff > git-diff.patch
      - uses: actions/upload-artifact@v4
        with:
          name: patch
          path: git-diff.patch

      # Capture the PR number
      - name: Create pr_number.txt
        run: echo "${{ github.event.number }}" > pr_number.txt
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number.txt
